version: '3.7'

services:

  quikuser_api:
    image: ${IMAGE_NAME:-quikuser}
    build:
        context: ./
    container_name: ${CONTAINER_NAME:-quikuser}
    privileged: true
    restart: always
    networks:
        - net-quikuser
    ports:
        - "3000:3000"
    volumes:
        - ./:/var/quikuser/
  quikuser_db:
    container_name: ${CONTAINER_NAME:-quikuserdb}
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: quikuser
      MONGO_INITDB_ROOT_PASSWORD: quikuserPWD
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
        - net-quikuser
# DEV Network
networks:
  net-quikuser:
    name: net-quikuser
    driver: bridge